name = "light_arduino_due"
description = "Arduino Due Board Support Package for `light` GNAT Runtime"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]

project-files=["gnat/arduino_due_startup.gpr"]

tags = ["embedded", "bsp", "light", "sam3x8e", "arduino", "due"]

[configuration]
disabled = true

[[depends-on]]
gnat_arm_elf = "*"
