name = "light_stm32f4_disco"
description = "STM32F4 DISCOVERY Board Support Package for `light` GNAT Runtime"
version = "0.1.0-dev"

authors = ["Yuri Veretelnikov"]
maintainers = ["Yuri Veretelnnikov <yuri.veretelnikov@gmail.com>"]
maintainers-logins = ["meowthsli"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["../gnat/light_stm32f4_disco.gpr"]

tags = ["embedded", "bsp", "light", "stm32", "stm32f4", "disco", "discovery", "stm32f4disco"]

[configuration]
disabled = true

[configuration.values]
a0b_armv7m.fpu_extension = "VFPv4"

[[depends-on]]
gnat_arm_elf = "*"
a0b_armv7m = "*"
a0b_stm32f407 = "*"
