name = "light_fk723m1_zgt6"
description = "FK723M1-ZGT6 Board Support Package for `light` GNAT Runtime"
version = "0.2.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

tags = ["a0b", "embedded", "bsp", "light", "stm32h723", "fk723m1"]

project-files=["../gnat/light_fk723m1_zgt6.gpr"]

[configuration]
disabled = true

[configuration.values]
a0b_armv7m.fpu_extension = "VFPv5"

[[depends-on]]
a0b_stm32h723 = "*"
